[build]
  functions = "functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/api/:splat"
  status = 200

[[redirects]]
  from = "/proxy"
  to = "/.netlify/functions/server/proxy"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
